server:
  port: 8080
  servlet:
    context-path: /santander

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: cyjbpvtlulnxkw
    password: c975e5fa768166923b9b25b27bc54384883d4abcfc8bd6fd9ea72264882b036f
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto feito durante SantaderDevWeek - SantanderAPI